[package]
name = "landmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
encase = { version = "0.6.1", features = ["glam"] }
env_logger = "0.10.0"
game-loop = { version = "0.10.2", features = ["winit"] }
glam = "0.24.1"
pollster = "0.3.0"
sparsey = "0.11.0"
wgpu = "0.17.0"
